Al-Ain/AL-Ain Doc Drive/Search n View/Controllers/DocumentTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Search_n_View.ViewModels;
using Search_n_View.Models;
using System.Threading.Tasks;
using System.Data.Entity;

namespace Search_n_View.Controllers
{
    public class DocumentTypeController : Controller
    {
        // GET: DocumentType
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            try
            {
                var DTypes = db.DocumentType.OrderByDescending(x => x.Id).Where(x => x.IsDeleted == false).ToList();

                var DtVM = new List<DocumentTypeViewModel>();
                for (int i = 0; i < DTypes.Count; i++)
                {
                    var Dt = new DocumentTypeViewModel();

                    Dt.Id = DTypes[i].Id;
                    Dt.Name = DTypes[i].Name;
                    Dt.ItemTypeName = DTypes[i].ItemType.Name;
                    Dt.AddedTime = DTypes[i].AddedTime;
                    Dt.ModifiedTime = DTypes[i].ModifiedTime;
                    Dt.CreatedBy = DTypes[i].AddedBy;
                    Dt.ModifiedBy = DTypes[i].ModifiedBy;
                    DtVM.Add(Dt);
                }

                var model = new ManageDocumentTypeViewModel();
                model.DocumentType = DtVM;
                return View(model);
            }
            catch (Exception ex)
            {
                Helpers.Logs.ErrorLog("DocumentTypeController", "Index", ex.Message, ex.Source, ex.StackTrace);
                return View();
            }
        }

        [Authorize(Roles = "PowerAdmin, Admin")]
        public ActionResult Create()
        {
            try
            {
                var model = new DocumentTypeViewModel();
                var ITyps = db.ItemType.ToList();
                model.ItemTypes = ITyps.Select(s => new SelectListItem { Value = Convert.ToString(s.Id), Text = s.Name }).ToList();
                return View(model);
            }
            catch (Exception ex)
            {
                Helpers.Logs.ErrorLog("DocumentTypeController", "Create", ex.Message, ex.Source, ex.StackTrace);
                return View(new DocumentTypeViewModel());
            }
        }

        [HttpPost]
        [Authorize(Roles = "PowerAdmin, Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(DocumentTypeViewModel IType)
        {
            try
            {
                var model = new DocumentType();

                if (ModelState.IsValid)
                {
                    string CurrentUserName = User.Identity.Name;

                    var doc = db.DocumentType.Where(x => x.Name == IType.Name.Trim()).Where(x => x.IsDeleted == false).FirstOrDefault();
                    if (doc == null)
                    {
                        model.Name = IType.Name;
                        model.ItID = IType.ItId;
                        model.AddedTime = DateTime.Now;
                        model.ModifiedTime = DateTime.Now;
                        model.AddedBy = CurrentUserName;
                        model.ModifiedBy = CurrentUserName;

                        db.DocumentType.Add(model);
                        await db.SaveChangesAsync();

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        var Items = db.ItemType.ToList();
                        IType.ItemTypes = Items.Select(s => new SelectListItem { Value = Convert.ToString(s.Id), Text = s.Name }).ToList();
                        ViewData["Message"] = "Item Type Already Exist!";
                        return View(IType);

                    }


                }
                else
                {
                    var Items = db.ItemType.ToList();
                    IType.ItemTypes = Items.Select(s => new SelectListItem { Value = Convert.ToString(s.Id), Text = s.Name }).ToList();
                    return View(IType);
                }

            }
            catch (Exception ex)
            {
                Helpers.Logs.ErrorLog("DocumentTypeController", "Create", ex.Message, ex.Source, ex.StackTrace);
                return View(new DocumentTypeViewModel());
            }
        }


        [Authorize(Roles = "PowerAdmin, Admin")]
        public ActionResult Edit(EditDocumentTypeIdViewModel mod)
        {
            try
            {
                var IType = db.ItemType.ToList();
                var DocType = db.DocumentType.Find(mod.Id);
                var model = new EditDocumentTypeIdViewModel();

                model.Name = DocType.Name;
                model.ItId = Convert.ToInt32(DocType.ItemType.Id);
                ViewBag.ItId = new SelectList(IType, "Id", "Name", model.ItId);
                model.AddedTime = DocType.AddedTime;
                model.ModifiedTime = DocType.ModifiedTime;
                model.CreatedBy = DocType.AddedBy;
                model.ModifiedBy = DocType.ModifiedBy;

                return View(model);

            }
            catch (Exception ex)
            {
                Helpers.Logs.ErrorLog("DocumentTypeController", "Edit", ex.Message, ex.Source, ex.StackTrace);
                return View(new EditDocumentTypeIdViewModel());
            }
        }

        [HttpPost]
        [Authorize(Roles = "PowerAdmin, Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditDocumentTypeViewModel It)
        {
            try
            {
                string CurrentUserName = User.Identity.Name;
                var IType = db.DocumentType.Find(It.Id);
                var model = new EditDocumentTypeIdViewModel();
                model.Name = It.Name;

                if (ModelState.IsValid)
                {
                    IType.Name = It.Name;
                    IType.ItID = It.ItId;
                    IType.ModifiedTime = DateTime.Now;
                    IType.ModifiedBy = CurrentUserName;

                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                else
                    return View(model);

            }
            catch (Exception ex)
            {
                Helpers.Logs.ErrorLog("DocumentTypeController", "Edit", ex.Message, ex.Source, ex.StackTrace);
                return View(new EditDocumentTypeIdViewModel());
            }
        }

    }
}

Al-Ain/AL-Ain Doc Drive/Search n View/Views/DocumentType/Create.cshtml
@model Search_n_View.ViewModels.DocumentTypeViewModel
@{
    ViewBag.Title = "Create Branches";
    string message = Convert.ToString(ViewData["Message"]);
}


<div>
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-6">
                @using (Html.BeginForm("Create", "DocumentType", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    <div class="card">
                        <div class="card-header">
                            <h5>@ViewBag.Title</h5>
                        </div>
                        <div class="card-body">
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary("", new { @class = "text-danger" })

                            @if (message != "")
                            {
                                <div class="form-group row">
                                    <ul><li style="color: #f86c6b;">@message</li></ul>
                                </div>
                            }
                            <div class="form-group row">
                                @Html.LabelFor(m => m.Name, new { @class = "col-md-3 col-form-label font-weight-bold" })
                                <span style="color: #f86c6b;font-weight:bold;font-size:20px;">*</span>
                                <div class="col-md-8">
                                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @placeholder = "Enter Name" , tabindex = 1})
                                </div>
                            </div>
                            <div class="form-group row">
                                @Html.LabelFor(m => m.ItemTypes, new { @class = "col-md-3 col-form-label font-weight-bold" })
                                <span style="color: #f86c6b;font-weight:bold;font-size:20px;">*</span>
                                <div class="col-md-8">
                                    <select class="form-control" tabindex="2" name="ItId">
                                        <option value="0" >Select ItemType</option>
                                        @foreach (var obj in Model.ItemTypes)
                                        {
                                            if (obj.Text != "All")
                                            {
                                                <option value="@Convert.ToInt32(obj.Value)">@obj.Text</option>
                                            }
                                        }

                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-md btn-primary mr-3" type="submit">
                                <i class="fa fa-dot-circle-o"></i> Create
                            </button>
                            <a class="btn btn-md btn-primary ml-3" href="@Url.Action("Index", "DocumentType")">
                                <i class="fa fa-close"></i> Cancel
                            </a>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

Al-Ain/AL-Ain Doc Drive/Search n View/Views/DocumentType/Edit.cshtml
@model Search_n_View.ViewModels.EditDocumentTypeIdViewModel
@{
    ViewBag.Title = "Edit Branch";
}

<div>
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-6">
                @using (Html.BeginForm("Edit", "DocumentType", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    <div class="card">
                        <div class="card-header">
                            <h5>@ViewBag.Title</h5>
                        </div>
                        <div class="card-body">
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary("", new { @class = "text-danger" })
                            <div class="form-group row">
                                @Html.LabelFor(m => m.Name, new { @class = "col-md-3 col-form-label font-weight-bold" })
                                <span style="color: #f86c6b;font-weight:bold;font-size:20px;">*</span>
                                <div class="col-md-8">
                                    @Html.HiddenFor(m => m.Id, new { @class = "form-control" })
                                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", })
                                </div>
                            </div>
                            <div class="form-group row">

                                <label class="col-md-3 col-form-label font-weight-bold">Select Pharmacy</label>
                                <span style="color: #f86c6b;font-weight:bold;font-size:20px;">*</span>
                                <div class="col-md-8">
                                    @Html.DropDownList("ItId", null, htmlAttributes: new { @class = "form-control ItemTypeList", @title = "Select DepartmentList", tabindex = 2 })
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-md btn-primary mr-3" type="submit">
                                <i class="fa fa-dot-circle-o"></i> Save
                            </button>
                            <a class="btn btn-md btn-primary ml-3" href="@Url.Action("Index", "DocumentType")">
                                <i class="fa fa-close"></i> Cancel
                            </a>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

Al-Ain/AL-Ain Doc Drive/Search n View/Views/DocumentType/Index.cshtml
@model Search_n_View.ViewModels.ManageDocumentTypeViewModel
@{
    ViewBag.Title = "Manage Branches";
}

@section styles {
    <style>
        td .btn-primary, .btn-danger {
            padding: .175rem .55rem;
        }
    </style>
}
<div>
    <div class="animated fadeIn">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-list-alt"></i> Branches
                <div class="card-header-actions">
                    <a class="btn btn-info" href="@Url.Action("Create", "DocumentType")">
                        <i class="fa fa-plus"></i> Add Branch
                    </a>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-striped table-responsive-sm datatable">
                    <thead>
                        <tr>
                            <th class="text-center">Name</th>
                            <th class="text-center">Pharmacy</th>
                            <th class="text-center">AddedBy</th>
                            <th class="text-center">AddedDate</th>
                            <th class="no-sort text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var Item in Model.DocumentType)
                        {
                        <tr>

                            <td class="text-center">@Item.Name</td>
                            <td class="text-center">@Item.ItemTypeName</td>
                            <td class="text-center">@Item.CreatedBy</td>
                            <td class="text-center">@Item.AddedTime.ToString("dd MMM yyyy HH:mm")</td>

                            <td class="text-center">
                                <a class="btn btn-primary" title="Edit" href="@Url.Action("Edit", "DocumentType", new { Id = Item.Id })">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>