Al-Ain/AL-Ain Doc Drive/Search n View/Controllers/ItemTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Search_n_View.ViewModels;
using Search_n_View.Models;
using System.Threading.Tasks;
using System.Data.Entity;

namespace Search_n_View.Controllers
{
    public class ItemTypeController : Controller
    {
        // GET: ItemType
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            try
            {
                var ITypes = db.ItemType.OrderByDescending(x => x.Id).Where(x => x.IsDeleted == false).ToList();

                var ItVM = new List<ItemTypeViewModel>();
                for (int i = 0; i < ITypes.Count; i++)
                {
                    var It = new ItemTypeViewModel();

                    It.Id = ITypes[i].Id;
                    It.Name = ITypes[i].Name;
                    It.DepartmentName = ITypes[i].MainDepartment.Name;
                    It.AddedTime = ITypes[i].AddedTime;
                    It.ModifiedTime = ITypes[i].ModifiedTime;
                    It.CreatedBy = ITypes[i].AddedBy;
                    It.ModifiedBy = ITypes[i].ModifiedBy;
                    ItVM.Add(It);
                }

                var model = new ManageItemTypeViewModel();
                model.ItemType = ItVM;
                return View(model);
            }
            catch (Exception ex)
            {
                Helpers.Logs.ErrorLog("ItemTypeController", "Index", ex.Message, ex.Source, ex.StackTrace);
                return View();
            }
        }

        [Authorize(Roles = "PowerAdmin, Admin")]
        public ActionResult Create()
        {
            try
            {
                var model = new ItemTypeViewModel();
                var depts = db.MainDepartment.ToList();
                model.Departments = depts.Select(s => new SelectListItem { Value = Convert.ToString(s.Id), Text = s.Name }).ToList();
                return View(model);
            }
            catch (Exception ex)
            {
                Helpers.Logs.ErrorLog("ItemTypeController", "Create", ex.Message, ex.Source, ex.StackTrace);
                return View(new ItemTypeViewModel());
            }
        }

        [HttpPost]
        [Authorize(Roles = "PowerAdmin, Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ItemTypeViewModel IType)
        {
            try
            {
                var model = new ItemType();

                if (ModelState.IsValid)
                {
                    string CurrentUserName = User.Identity.Name;

                    var doc = db.ItemType.Where(x => x.Name == IType.Name.Trim()).Where(x => x.IsDeleted == false).FirstOrDefault();
                    if (doc == null)
                    {
                        model.Name = IType.Name;
                        model.MdId = IType.MdId;
                        model.AddedTime = DateTime.Now;
                        model.ModifiedTime = DateTime.Now;
                        model.AddedBy = CurrentUserName;
                        model.ModifiedBy = CurrentUserName;

                        db.ItemType.Add(model);
                        await db.SaveChangesAsync();

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        var depts = db.MainDepartment.ToList();
                        IType.Departments = depts.Select(s => new SelectListItem { Value = Convert.ToString(s.Id), Text = s.Name }).ToList();
                        ViewData["Message"] = "Item Type Already Exist!";
                        return View(IType);

                    }
                }
                else
                {
                    var depts = db.MainDepartment.ToList();
                    IType.Departments = depts.Select(s => new SelectListItem { Value = Convert.ToString(s.Id), Text = s.Name }).ToList();
                    return View(IType);
                }

            }
            catch (Exception ex)
            {
                Helpers.Logs.ErrorLog("ItemTypeController", "Create", ex.Message, ex.Source, ex.StackTrace);
                return View(new ItemTypeViewModel());
            }
        }


        [Authorize(Roles = "PowerAdmin, Admin")]
        public ActionResult Edit(EditItemTypeIdViewModel mod)
        {
            try
            {
                var depts = db.MainDepartment.ToList();
                var IType = db.ItemType.Find(mod.Id);
                var model = new EditItemTypeIdViewModel();

                model.Name = IType.Name;
                model.MdId = IType.MainDepartment.Id;
                ViewBag.MdId = new SelectList(depts, "Id", "Name", model.MdId);
                model.AddedTime = IType.AddedTime;
                model.ModifiedTime = IType.ModifiedTime;
                model.CreatedBy = IType.AddedBy;
                model.ModifiedBy = IType.ModifiedBy;

                return View(model);

            }
            catch (Exception ex)
            {
                Helpers.Logs.ErrorLog("ItemTypeController", "Edit", ex.Message, ex.Source, ex.StackTrace);
                return View(new EditItemTypeIdViewModel());
            }
        }

        [HttpPost]
        [Authorize(Roles = "PowerAdmin, Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditItemTypeViewModel It)
        {
            try
            {
                string CurrentUserName = User.Identity.Name;
                var IType = db.ItemType.Find(It.Id);
                var model = new EditItemTypeIdViewModel();
                model.Name = It.Name;

                if (ModelState.IsValid)
                {
                    IType.Name = It.Name;
                    IType.MdId = It.MdId;
                    IType.ModifiedTime = DateTime.Now;
                    IType.ModifiedBy = CurrentUserName;

                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                else
                    return View(model);

            }
            catch (Exception ex)
            {
                Helpers.Logs.ErrorLog("ItemTypeController", "Edit", ex.Message, ex.Source, ex.StackTrace);
                return View(new EditItemTypeIdViewModel());
            }
        }

    }
}

Al-Ain/AL-Ain Doc Drive/Search n View/Views/ItemType/Create.cshtml
@model Search_n_View.ViewModels.ItemTypeViewModel
@{
    ViewBag.Title = "Create Item Type";
    string message = Convert.ToString(ViewData["Message"]);
}


<div>
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-6">
                @using (Html.BeginForm("Create", "ItemType", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    <div class="card">
                        <div class="card-header">
                            <h5>@ViewBag.Title</h5>
                        </div>
                        <div class="card-body">
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary("", new { @class = "text-danger" })

                            @if (message != "")
                            {
                                <div class="form-group row">
                                    <ul><li style="color: #f86c6b;">@message</li></ul>
                                </div>
                            }
                            <div class="form-group row">
                                @Html.LabelFor(m => m.Name, new { @class = "col-md-3 col-form-label font-weight-bold" })
                                <span style="color: #f86c6b;font-weight:bold;font-size:20px;">*</span>
                                <div class="col-md-8">
                                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @placeholder = "Enter Name" })
                                </div>
                            </div>
                            <div class="form-group row">
                                @Html.LabelFor(m => m.Departments, new { @class = "col-md-3 col-form-label font-weight-bold" })
                                <span style="color: #f86c6b;font-weight:bold;font-size:20px;">*</span>
                                <div class="col-md-8">
                                    <select class="form-control" tabindex="2" name="MdId">
                                        <option value="0">Select Department</option>
                                        @foreach (var obj in Model.Departments)
                                        {
                                            if (obj.Text != "All")
                                            {
                                                <option value="@Convert.ToInt32(obj.Value)">@obj.Text</option>
                                            }
                                        }

                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-md btn-primary mr-3" type="submit">
                                <i class="fa fa-dot-circle-o"></i> Create
                            </button>
                            <a class="btn btn-md btn-primary ml-3" href="@Url.Action("Index", "ItemType")">
                                <i class="fa fa-close"></i> Cancel
                            </a>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

Al-Ain/AL-Ain Doc Drive/Search n View/Views/ItemType/Edit.cshtml
@model Search_n_View.ViewModels.EditItemTypeIdViewModel
@{
    ViewBag.Title = "Edit Pharmacy";
}

<div>
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-6">
                @using (Html.BeginForm("Edit", "ItemType", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    <div class="card">
                        <div class="card-header">
                            <h5>@ViewBag.Title</h5>
                        </div>
                        <div class="card-body">
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary("", new { @class = "text-danger" })
                            <div class="form-group row">
                                @Html.LabelFor(m => m.Name, new { @class = "col-md-3 col-form-label font-weight-bold" })
                                <span style="color: #f86c6b;font-weight:bold;font-size:20px;">*</span>
                                <div class="col-md-8">
                                    @Html.HiddenFor(m => m.Id, new { @class = "form-control" })
                                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label font-weight-bold">Select Department</label>
                                <span style="color: #f86c6b;font-weight:bold;font-size:20px;">*</span>
                                <div class="col-md-8">
                                    @Html.DropDownList("MdId",null, htmlAttributes: new { @class = "form-control DepartmentList", @title = "Select DepartmentList", tabindex = 2 })
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-md btn-primary mr-3" type="submit">
                                <i class="fa fa-dot-circle-o"></i> Save
                            </button>
                            <a class="btn btn-md btn-primary ml-3" href="@Url.Action("Index", "ItemType")">
                                <i class="fa fa-close"></i> Cancel
                            </a>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

Al-Ain/AL-Ain Doc Drive/Search n View/Views/ItemType/Index.cshtml
@model Search_n_View.ViewModels.ManageItemTypeViewModel
@{
    ViewBag.Title = "Manage Pharmacies";
}

@section styles {
    <style>
        td .btn-primary, .btn-danger {
            padding: .175rem .55rem;
        }
    </style>
}
<div>
    <div class="animated fadeIn">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-list-alt"></i> Pharmacy
                <div class="card-header-actions">
                    <a class="btn btn-info" href="@Url.Action("Create", "ItemType")">
                        <i class="fa fa-plus"></i> Add Pharmacy
                    </a>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-striped table-responsive-sm datatable">
                    <thead>
                        <tr>
                            <th class="text-center">Name</th>
                            <th class="text-center">Department</th>
                            <th class="text-center">AddedBy</th>
                            <th class="text-center">AddedDate</th>
                            <th class="no-sort text-center">Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var Item in Model.ItemType)
                        {
                           if (Item.Name != "All")
                            {
                                <tr>

                                    <td class="text-center">@Item.Name</td>

                                    <td class="text-center">@Item.DepartmentName</td>

                                    <td class="text-center">@Item.CreatedBy</td>

                                    <td class="text-center">@Item.AddedTime.ToString("dd MMM yyyy HH:mm")</td>


                                    <td class="text-center">
                                        <a class="btn btn-primary" title="Edit" href="@Url.Action("Edit", "ItemType", new { Id = Item.Id })">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    </td>
                                </tr>
                                }
                            }
                        </tbody>
                </table>
            </div>
        </div>
    </div>
</div>