Al-Ain/AL-Ain Doc Drive/Search n View/Models/Document.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Search_n_View.Models
{
    public class Document: BaseModel
    {
        public string DocPath { get; set; }
        public string ClaimNo { get; set; }    

        [ForeignKey("ItemType")]
        public int ItID { get; set; }
        public virtual ItemType ItemType { get; set; }

        [ForeignKey("DocumentType")]
        public int DtId { get; set; }
        public virtual DocumentType DocumentType { get; set; }

        [ForeignKey("EmailAttachment")]
        public int? DEId { get; set; }
        public virtual EmailAttachment EmailAttachment { get; set; }

        [ForeignKey("User")]
        public string UId { get; set; }
        public virtual ApplicationUser User { get; set; }

        public string PolicyNo { get; set; }

        public string Email { get; set; }

        public string ScannedFilePath { get; set; }
        public string Year { get; set; }
        public string Extension { get; set; }
        public bool? IsActive { get; set; }
        public string BaseDrivePath { get; set; }

        public DateTime? Date { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }

    }
}

Al-Ain/AL-Ain Doc Drive/Search n View/Models/DocumentType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Search_n_View.Models
{
    public class DocumentType : BaseModel
    {
        public string Name { get; set; }

        [ForeignKey("ItemType")]
        public int? ItID { get; set; }
        public virtual ItemType ItemType { get; set; }
    }
}

Al-Ain/AL-Ain Doc Drive/Search n View/Controllers/DocumentController.cs
using Microsoft.AspNet.Identity;
using MsgReader.Outlook;
using Search_n_View.Models;
using Search_n_View.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Printing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Services.Description;
using System.Windows.Forms;
using WIA;

namespace Search_n_View.Controllers
{
    public class DocumentController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        public ActionResult DocumentSearch()
        {
            try
            {
                var SessionUserId = User.Identity.GetUserId();

                if (User.IsInRole("SearchUser"))
                {
                    var ItemTypeList = (from uit in db.UserItemType
                                        join It in db.ItemType
                                        on uit.ItID equals It.Id
                                        where uit.UID == SessionUserId
                                        && It.IsDeleted == false
                                        select It).ToList();
                    ViewBag.ItemTypeList = ItemTypeList;
                    var DepartmentList = (from uit in db.UserDepartment
                                        join It in db.MainDepartment
                                        on uit.MdID equals It.Id
                                        where uit.UID == SessionUserId
                                        && It.IsDeleted == false
                                        select It).ToList();

                    ViewBag.DepartmentList = DepartmentList;
                    var DocTypeIds = (from uit in db.UserItemType
                                      join it in db.ItemType
                                      on uit.ItID equals it.Id
                                      join dt in db.DocumentType
                                      on it.Id equals dt.ItID
                                      where uit.UID == SessionUserId
                                      select dt.Id).ToList();

                    ViewBag.DocTypeIds = DocTypeIds;
                }
                else {
                    var DepartmentList = db.MainDepartment.Where(x=>x.IsDeleted == false).ToList();                  
                    ViewBag.DepartmentList = DepartmentList;
                    ViewBag.ItemTypeList = new List<ItemType>();
                    ViewBag.DocTypeIds = new List<DocumentType>();

                }


                ViewData["DocList"] = null;
                return View();
            }
            catch (Exception ex)
            {
                Helpers.Logs.ErrorLog("DocumentController", "DocumentSearch", ex.Message, ex.Source, ex.StackTrace);
                return View();
            }
        }

        [HttpPost]
        public PartialViewResult DocumentFilter(string Channel, string InvoiceNo, string FromDate, string ToDate, int? itemTypeId, int? DepartId, int? docTypeId)
        {
            try
            {
                DateTime? From = null;
                DateTime? To = null;
                if (!string.IsNullOrEmpty(FromDate))
                {
                    FromDate = FromDate + " " + "00:00:00";
                    From = Convert.ToDateTime(FromDate);
                }
                if (!string.IsNullOrEmpty(ToDate))
                {
                    ToDate = ToDate + " " + "23:59:59";
                    To = Convert.ToDateTime(ToDate);
                }
                var SessionUserId = User.Identity.GetUserId();
                string CurrentUserName = User.Identity.Name;

                if (CurrentUserName != null && CurrentUserName != "")
                {
                    try
                    {
                        if (User.IsInRole("SearchUserApprove"))
                        {
                            var tblAlAinDocument = db.AlAinDocument.Where(x => x.IsApproved != true).ToList();

                            if (Channel!="0")
                            {
                                tblAlAinDocument = tblAlAinDocument.Where(x => x.ChannelName.Contains(Channel)).ToList();
                            }
                            if (!string.IsNullOrEmpty(InvoiceNo))
                            {
                                tblAlAinDocument = tblAlAinDocument.Where(x => x.InvoiceNo.Contains(InvoiceNo)).ToList();
                            }
                            if (!string.IsNullOrEmpty(FromDate) && !string.IsNullOrEmpty(ToDate))
                            {
                                DateTime fromDateValue;
                                DateTime toDateValue;
                                if (DateTime.TryParse(FromDate, out fromDateValue) && DateTime.TryParse(ToDate, out toDateValue))
                                {
                                    tblAlAinDocument = tblAlAinDocument.Where(x => x.InvoiceDate >= fromDateValue && x.InvoiceDate <= toDateValue).ToList();
                                }
                            }
                            if (itemTypeId != 0)
                            {
                                tblAlAinDocument = tblAlAinDocument.Where(x => x.ItID == itemTypeId).ToList();
                            }
                            if (docTypeId != 0)
                            {
                                tblAlAinDocument = tblAlAinDocument.Where(x => x.DtId == docTypeId).ToList();
                            }
                            if (DepartId !=0)
                            {
                                tblAlAinDocument = tblAlAinDocument.Where(x => x.MdId == DepartId).ToList();
                            }

                            ViewData["DocList"] = tblAlAinDocument; 
                        }
                        else
                        {
                            var tblAlAinDocument = db.AlAinDocument.ToList();
                            if (Channel != "0")
                            {
                                tblAlAinDocument = tblAlAinDocument.Where(x => x.ChannelName.Contains(Channel)).ToList();
                            }
                            if (!string.IsNullOrEmpty(InvoiceNo))
                            {
                                tblAlAinDocument = tblAlAinDocument.Where(x => x.InvoiceNo.Contains(InvoiceNo)).ToList();
                            }

                            if (!string.IsNullOrEmpty(FromDate) && !string.IsNullOrEmpty(ToDate))
                            {
                                DateTime fromDateValue;
                                DateTime toDateValue;
                                if (DateTime.TryParse(FromDate, out fromDateValue) && DateTime.TryParse(ToDate, out toDateValue))
                                {
                                    tblAlAinDocument = tblAlAinDocument.Where(x => x.InvoiceDate >= fromDateValue && x.InvoiceDate <= toDateValue).ToList();
                                }
                            }
                            if (itemTypeId != 0)
                            {
                                tblAlAinDocument = tblAlAinDocument.Where(x => x.ItID == itemTypeId).ToList();
                            }
                            if (docTypeId != 0)
                            {
                                tblAlAinDocument = tblAlAinDocument.Where(x => x.DtId == docTypeId).ToList();
                            }
                            if (DepartId != 0)
                            {
                                tblAlAinDocument = tblAlAinDocument.Where(x => x.MdId == DepartId).ToList();
                            }
                            ViewData["DocList"] = tblAlAinDocument;

                        }
                        var Access = db.Users.Include(x => x.AccessGroup).Where(x => x.Id == SessionUserId).FirstOrDefault();
                        ViewBag.Access = Access;
                    }
                    catch (Exception ex)
                    {
                        Helpers.Logs.ErrorLog("DocumentController", "DocumentFilter", ex.Message, ex.Source, ex.StackTrace);
                        return PartialView("~/Views/Shared/_DocList.cshtml");
                    }

                }
                else
                {
                    List<Document> Doc = new List<Document>();
                    ViewData["DocList"] = Doc;
                }


                return PartialView("~/Views/Shared/_DocList.cshtml");
            }
            catch (Exception ex)
            {
                Helpers.Logs.ErrorLog("DocumentController", "DocumentFilter", ex.Message, ex.Source, ex.StackTrace);
                return PartialView("~/Views/Shared/_DocList.cshtml");
            }
        }

        [HttpPost]
        public JsonResult SingleDocumentUpload(Document Doc, EmailSender EmailDetail, string ScannedDocPath)
        {
            try
            {
                var SessionUserId = User.Identity.GetUserId();
                var SessionUserName = User.Identity.Name;
                string CurrentUserName = Convert.ToString(SessionUserName);
                if (CurrentUserName != null && CurrentUserName != "")
                {
                    var check = db.Document.Where(x => x.ClaimNo == Doc.ClaimNo && x.PolicyNo == Doc.PolicyNo && x.ItID == Doc.ItID && x.DtId == Doc.DtId).FirstOrDefault();
                    if (check == null)
                    {
                        EmailAttachment E = null;

Al-Ain/AL-Ain Doc Drive/Search n View/Views/Document/AccessHistory.cshtml
@using Search_n_View.ViewModels;
@{
    ViewBag.Title = "Access History";
    List<UserDocument> DocViewers = ViewData["DocViewers"] as List<UserDocument>;
    var Users = ViewBag.Users;
    var ItemTypeList = ViewBag.ItemTypeList;
    var DocumentTypeList = ViewBag.DocumentTypeList;
}

@section styles {
    <style>
        td .btn-primary {
            padding: .175rem .55rem;
        }

        #Users:focus {
            outline: 3px solid #ddd;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #fff;
            min-width: 289px;
            overflow: auto;
            z-index: 1;
            border: 1px solid gray;
        }

        .dropdown a:hover {
            background-color: #ddd;
        }

        .show {
            display: block;
        }

        .dropdown-content a {
            color: dimgray;
            padding: 0px 10px;
            text-decoration: none;
            display: block;
            background-color: #fff;
            cursor: pointer;
        }
    </style>
    <link href="~/Content/daterangepicker.min.css" rel="stylesheet" />
}



<div class="row col-md-12 ">
    <h5>Viewed Documents</h5>
</div>

<div class="DocumentViewers">
    <div class="row">
        <div class="col-md-12">
            <div class="card ">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-3">
                                    <input type="text" name="dates" class="form-control DocFilters DocFilterDate" placeholder="Date Range" />
                                    <input type="hidden" class="DateSelected" value="0">
                                </div>
                                <div class="col-md-3">
                                    <div class="dropdown">
                                        <input type="text" style="background-color:#fff;color: dimgray;" data-userid="" class="form-control" placeholder="Users" id="Users" onkeyup="filterFunction()" autocomplete="off">
                                        <div id="myDropdown" class="dropdown-content">
                                            @for (int i = 0; i < Users.Count; i++)
                                            {
                                                if (Users[i].UserName != null)
                                                {
                                                    <a class="UserName" data-userid="@Users[i].Id">@Users[i].UserName</a>
                                                }

                                            }
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <select class="form-control ItemTypeList">
                                        <option value="0" data-shortname="0">Select Pharmacy</option>
                                        @for (int i = 0; i < ItemTypeList.Count; i++)
                                        {
                                            if (ItemTypeList[i].Name != "All")
                                            {
                                                <option value="@ItemTypeList[i].Id">@ItemTypeList[i].Name</option>
                                            }

                                        }
                                    </select>
                                </div>
                                <div class="col-md-3">
                                    <select class="form-control DocumentTypeList">
                                        <option value="0" >Select Branch</option>
                                       
                                        
                                    </select>
                                </div>


                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <button id="FilterDocViewers" class="btn-primary" style="margin-top:10px;width:100%;">Filter</button>
                        </div>
                    </div>
                </div>
                <div class="card-body AllDocViewers">
                    <div class="table-responsive">
                        <table class="table table-striped datatable">
                            <thead>
                                <tr>
                                    @*<th class="text-center">VesselNo</th>*@
                                    <th class="text-center">InvocieNo</th>
                                    <th class="text-center">Pharmacy</th>
                                    <th class="text-center">Branch</th>
                                    <th class="text-center">ViewedBy</th>
                                    <th class="text-center">ViewedTime</th>

                                </tr>
                            </thead>
                            <tbody class="AllDocViewersData">
                                @if (DocViewers != null)
                                {

                                }
                                else
                                {
                                    <tr>
                                        <td class="text-center" colspan="6">No Record Foound</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

@section Scripts {
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/daterangepicker.js"></script>
    <script>
    $(document).ready(function () {
         $('.DocFilterDate').daterangepicker({
                locale: {
                      format: 'DD/MM/YYYY',
                }

            });

          $(document).on("click", ".applyBtn", function () {
                $(".DateSelected").val(1);
          })

        
           $(document).on("click", ".cancelBtn", function () {
                    $('.DocFilterDate').val("");
                $('.DocFilterDate').daterangepicker({
                    locale: {
                        format: 'DD/MM/YYYY'
                    }
                });
                   $(".DateSelected").val(0);
           })

        $(document).on("click", "#Users", function () {
            if ($("#myDropdown").hasClass('show')) {
                $("#myDropdown").removeClass("show");
            } else {
                $("#myDropdown").addClass("show");
            }
        })


        $(document).on("click", ".UserName", function () {
            $("#Users").val($(this).text());
            $("#Users").data('userid', $(this).data('userid'));
            $("#myDropdown").removeClass("show");
        })

        $(document).on("click", function (e) {
            if (e.target.className !== "form-control") {
                $("#myDropdown").removeClass("show");
            };
        })


          $(".ItemTypeList").change(function () {
                if ($(".ItemTypeList option:selected").val() > 0) {
                     $(".DocumentTypeList").html(""); 
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("GetUserDocTypes","Document")',
                        data: { ItemTypeId: parseInt($(".ItemTypeList option:selected").val()) },
                        success: function (data) {
                            var html = "<option value='0'>Select DocumentType</option>";
                            for (var i = 0; i < data.length; i++) {                              
                                    html += "<option value=" + data[i].Id + ">" + data[i].Name + "</option>";                              
                            }
                            $(".DocumentTypeList").append(html);                           
                        }
                    });
                }
                
            })

        $(document).on("click", "#FilterDocViewers", function () {
            var DocDates;
            var FromDate = "";
            var ToDate = "";
            if ($(".DateSelected").val() > 0) {
                DocDates = $(".DocFilterDate").val();
                DocDates = DocDates.split(' - ')
                FromDate = DocDates[0].split('/');
                FromDate = FromDate[1] + "/" + FromDate[0] + "/" + FromDate[2];

                ToDate = DocDates[1].split('/');
                ToDate = ToDate[1] + "/" + ToDate[0] + "/" + ToDate[2];

            }


               var UserId = $("#Users").data('userid');
               var itid = $(".ItemTypeList option:selected").val();
            var dtid = $(".DocumentTypeList option:selected").val();

                    $.ajax({
                            type: 'POST',
                            url: '@Url.Action("AccessHistoryFiltered","Document")',
                            beforeSend: function () {
                                $("#cover-spin").show();
                            },
                            data: { From: FromDate, To: ToDate, UId: UserId, ItId: itid, DtId: dtid },
                            complete: function () {
                                setTimeout(function () { $("#cover-spin").hide(); }, 1000);
                            },
                            success: function (data) {
                                if (data != null) {
                                    if (data.length > 0) {
                                        $(".AllDocViewers").html("");
                                        $(".AllDocViewers").html(data);
                                        $('.datatable').DataTable({ "paging": true, "info": true, "ordering": false, "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]], "language": { "emptyTable": "No Record Found" } }); $('.datatable').attr('style', 'border-collapse: collapse !important');
                                    }
                                }
                                if ($(".AllDocViewersData").find("tr").length == 0)
                                    $(".AllDocViewersData").html("<tr><td class='text-center' colspan='5'>No Record Foound</td></tr>");
                            }
                        })

            })


          $('#Users').keyup(function () {
            if ($(this).val().length == 0)
               $(this).data("userid", "");
            })

    })

      function filterFunction() {
          var input, filter, ul, li, a, i, content;
              content = document.getElementById("myDropdown");
              content.classList.add('show');
            input = document.getElementById("Users");
            filter = input.value.toUpperCase();
            div = document.getElementById("myDropdown");
            a = div.getElementsByTagName("a");
            for (i = 0; i < a.length; i++) {
            txtValue = a[i].textContent || a[i].innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                a[i].style.display = "block";
            } else {
                a[i].style.display = "none";
            }
            }
    }

    </script>
}

Al-Ain/AL-Ain Doc Drive/Search n View/Views/Document/BulkMetaUpload.cshtml
@{
    ViewBag.Title = "BulkMetaUpload";
}

<h3>Bulk Meta Data Upload</h3>

<div class="row">
    <div class="col-md-6">
        <button style="" class="btn btn-primary BulkUpload" data-toggle="modal" data-target="#UploadBulk">Bulk Upload</button>
    </div>
</div>

<div class="modal fade" id="UploadBulk" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md modal-primary" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Bulk Data Upload</h4>
                <button class="close closeModal" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <input type="file" id="BulkUpload" data-bulkfileupload="" name="file">
                    <button type="button" class="btn btn-primary BulkDataUpload" data-dismiss="modal" style="display:none;">Upload</button>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-warning closeModal" type="button" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
    <!-- /.modal-content-->
</div>

@section Scripts {

    <script>
        $(document).ready(function () {

            $("#BulkUpload").change(function () {
                var fileUpload = $("#BulkUpload").get(0);
                var files = fileUpload.files;
                var fileData = new FormData();
                for (var i = 0; i < files.length; i++) {
                    fileData.append(files[i].name, files[i]);
                }
                fileData.append('BulkFile', 'csvFile');
                $(this).data("bulkfileupload", fileData);

                if ($("#BulkUpload").data("bulkfileupload") != "")
                    $(".BulkDataUpload").fadeIn();
                else
                    $(".BulkDataUpload").hide();
            })

            $(document).on("click", ".BulkDataUpload", function () {

                var BulkUpload = $("#BulkUpload").data("bulkfileupload");
                if (BulkUpload != "") {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("BulkDataUpload", "Document")',
                        processData: false,
                        contentType: false,
                        data: BulkUpload,
                        beforeSend: function () {
                            $("#cover-spin").show();
                        },
                        complete: function () {
                            setTimeout(function () { $("#cover-spin").hide(); }, 1000);
                        },
                        success: function (data) {
                            if (data.DocCount > 0) {
                                $("#BulkUpload").val("");
                                $("#BulkUpload").data("bulkfileupload", "")
                                $(".BulkDataUpload").hide();
                                Swal.fire({
                                    title: '' + data.DocCount + ' Records!',
                                    text: 'Successfully Uploaded',
                                    type: 'success',
                                    showCancelButton: false,
                                    showConfirmButton: true
                                })

                            } else {
                                  Swal.fire({
                                    title: 'Warning',
                                    text: data.Message,
                                    type: 'warning',
                                    showCancelButton: false,
                                    showConfirmButton: true
                                })
                            }
                        }
                    })
                } else {
                    alert("Please Add File First.")
                }

            })

            $(document).on("click", ".closeModal", function () {
                $("#BulkUpload").val("");
                $("#BulkUpload").data("bulkfileupload", "");

                if ($("#BulkUpload").data("bulkfileupload") == "")
                    $(".BulkDataUpload").hide();

            })

        })
    </script>
    }

Al-Ain/AL-Ain Doc Drive/Search n View/Views/Document/CreateDocType.cshtml
@model Search_n_View.ViewModels.ManageDocumentTypesViewModel
@{
    ViewBag.Title = "Create Document Type";
    string message = Convert.ToString(ViewData["Message"]);
}


<div class="animated fadeIn">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            @using (Html.BeginForm("CreateDocType", "Document", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                <div class="card">
                    <div class="card-header">
                        <strong>Create New Document Type</strong>
                    </div>
                    <div class="card-body">
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary("", new { @class = "text-danger" })

                        @if (message != "")
                        {
                            <div class="form-group row">
                                <ul><li style="color: #f86c6b;">@message</li></ul>
                            </div>
                        }
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label font-weight-bold">Type</label>
                        <span style="color: #f86c6b;font-weight:bold;font-size:20px;">*</span>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.Type, new { @class = "form-control ", @placeholder = "Enter Name" ,tabindex = 1})
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label font-weight-bold">Code</label>
                        <span style="color: #f86c6b;font-weight:bold;font-size:20px;">*</span>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.DocumentTypeCode, new { @class = "form-control", @placeholder = "Enter Code" ,tabindex = 2})
                        </div>
                    </div>
                        <div class="form-group row">
                            <label class="col-md-2 col-form-label font-weight-bold" style="font-size:13.1px;">Category</label>
                            <span style="color: #f86c6b;font-weight:bold;font-size:20px;">*</span>
                            <div class="col-md-9">
                                @Html.DropDownListFor(model => model.DcId, Model.DocumentCategoryList, "Document Categories", htmlAttributes: new { @class = "form-control" ,tabindex = 3})
                            </div>
                        </div>

                    </div>
                    <div class="card-footer">
                        <button class="btn btn-md btn-primary mr-3" type="submit" tabindex = "4">
                            <i class="fa fa-dot-circle-o"></i> Create
                        </button>
                        <a class="btn btn-md btn-primary ml-3" href="@Url.Action("DocumentTypes", "Document")" tabindex = "5">
                            <i class="fa fa-close"></i> Cancel
                        </a>
                    </div>
                </div>
            }

        </div>
    </div>
</div>